# Generated by Django 3.2.25 on 2026-01-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_student_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Midterm', 'Midterm'), ('Model', 'Model'), ('End-Term', 'End-Term')], max_length=20)),
                ('mathematics', models.IntegerField()),
                ('science', models.IntegerField()),
                ('english', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
